import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Aperture,
  Armchair,
  BatteryCharging,
  Bluetooth,
  Bookmark,
  Camera,
  Cast,
  CircleDot,
  Compass,
  CreditCard,
  Crosshair,
  Disc,
  Disc2,
  Eye,
  Flame,
  Gauge,
  Hand,
  KeyRound,
  Layers,
  Lifebuoy,
  Lightbulb,
  Map,
  Package,
  ParkingSquare,
  Radar,
  Route,
  ScanEye,
  ShieldAlert,
  Smartphone,
  Snowflake,
  Sofa,
  Sparkle,
  Speaker,
  Sun,
  SunMoon,
  Thermometer,
  Tv,
  Video,
  Wind,
  type LucideIcon,
} from 'lucide-react-native';

export type OptionCategory = 'comfort' | 'safety' | 'multimedia' | 'seat' | 'exterior' | 'etc';

export interface CarOption {
  key: string;
  label: string;
  category: OptionCategory;
  icon: LucideIcon;
  description: string;
}

export const CATEGORY_LABEL: Record<OptionCategory, string> = {
  comfort: '편의',
  safety: '안전',
  multimedia: '멀티미디어',
  seat: '시트',
  exterior: '외관/휠',
  etc: '기타',
};

export const CATEGORY_ORDER: OptionCategory[] = [
  'safety',
  'comfort',
  'multimedia',
  'seat',
  'exterior',
  'etc',
];

export const CAR_OPTIONS: CarOption[] = [
  {
    key: 'rear_camera',
    label: '후방카메라',
    category: 'safety',
    icon: Camera,
    description: '후진할 때 차량 뒤쪽 화면을 모니터에 보여주는 카메라. 주차 시 사각 보완.',
  },
  {
    key: 'around_view',
    label: '어라운드뷰',
    category: 'safety',
    icon: ScanEye,
    description: '차량 4면 카메라 영상을 합성해 위에서 본 듯한 화면을 제공. 좁은 곳 주차에 유용.',
  },
  {
    key: 'front_sensor',
    label: '전방주차센서',
    category: 'safety',
    icon: Crosshair,
    description: '차량 앞 범퍼의 센서로 가까운 장애물을 감지해 경고음으로 알림.',
  },
  {
    key: 'rear_sensor',
    label: '후방주차센서',
    category: 'safety',
    icon: Radar,
    description: '후진 시 뒤쪽 장애물까지의 거리를 단계별 경고음으로 알림.',
  },
  {
    key: 'bsd',
    label: '사각지대경보',
    category: 'safety',
    icon: ShieldAlert,
    description: '사이드미러로 안 보이는 옆 차선 사각지대에 차량이 있을 때 경고.',
  },
  {
    key: 'lka',
    label: '차선유지보조',
    category: 'safety',
    icon: Route,
    description: '차로 중앙을 인식해 핸들을 자동으로 미세 조정. 장거리 운전 피로 감소.',
  },
  {
    key: 'acc',
    label: '어댑티브크루즈',
    category: 'safety',
    icon: Gauge,
    description: '앞 차와 일정 거리를 유지하며 속도를 자동으로 조절하는 크루즈.',
  },
  {
    key: 'aeb',
    label: '자동긴급제동',
    category: 'safety',
    icon: AlertTriangle,
    description: '전방 충돌 위험 감지 시 차량이 스스로 브레이크를 작동.',
  },
  {
    key: 'rear_cross_warn',
    label: '후측방경보',
    category: 'safety',
    icon: AlertCircle,
    description: '후진 출차 시 좌·우에서 접근하는 차량을 감지해 경고.',
  },
  {
    key: 'lane_depart_warn',
    label: '차선이탈경보',
    category: 'safety',
    icon: Compass,
    description: '방향지시등 없이 차로를 벗어나면 경고음·진동으로 알림.',
  },

  {
    key: 'smart_key',
    label: '스마트키',
    category: 'comfort',
    icon: KeyRound,
    description: '키를 주머니에 둔 채 도어 손잡이만 잡아 잠금 해제·시동이 가능.',
  },
  {
    key: 'sunroof',
    label: '선루프',
    category: 'comfort',
    icon: Sun,
    description: '지붕 일부가 열리는 유리창. 환기·채광용.',
  },
  {
    key: 'pano_sunroof',
    label: '파노라마선루프',
    category: 'comfort',
    icon: Aperture,
    description: '지붕 전체가 유리로 된 대형 선루프. 뒷좌석까지 채광.',
  },
  {
    key: 'auto_park',
    label: '자동주차',
    category: 'comfort',
    icon: ParkingSquare,
    description: '주차 공간을 인식해 차량이 스스로 핸들을 조작해 주차.',
  },
  {
    key: 'power_trunk',
    label: '전동트렁크',
    category: 'comfort',
    icon: Package,
    description: '버튼이나 발 동작으로 트렁크가 자동으로 열리고 닫힘.',
  },
  {
    key: 'wireless_charge',
    label: '무선충전패드',
    category: 'comfort',
    icon: BatteryCharging,
    description: '콘솔에 휴대폰을 올려두면 케이블 없이 무선 충전.',
  },
  {
    key: 'hud',
    label: 'HUD (헤드업)',
    category: 'comfort',
    icon: Eye,
    description: '차량 속도·내비 정보를 앞 유리에 투영해 시선을 떼지 않고 확인.',
  },
  {
    key: 'memory_seat',
    label: '메모리시트',
    category: 'comfort',
    icon: Bookmark,
    description: '운전자별 시트 위치를 저장해 버튼 한 번으로 복원.',
  },
  {
    key: 'cruise_control',
    label: '크루즈컨트롤',
    category: 'comfort',
    icon: Activity,
    description: '설정한 속도를 자동으로 유지. 고속도로 정속 주행에 유용.',
  },
  {
    key: 'auto_aircon',
    label: '자동에어컨',
    category: 'comfort',
    icon: Snowflake,
    description: '원하는 실내 온도를 설정하면 풍량과 풍향을 자동 조절.',
  },
  {
    key: 'epb',
    label: '전자식 파킹브레이크',
    category: 'comfort',
    icon: Disc2,
    description: '버튼 한 번으로 사이드브레이크를 작동·해제. 발판 사이드브레이크 대체.',
  },

  {
    key: 'navigation',
    label: '내비게이션',
    category: 'multimedia',
    icon: Map,
    description: '차량 내장 디스플레이의 길 안내 지도.',
  },
  {
    key: 'bluetooth',
    label: '블루투스',
    category: 'multimedia',
    icon: Bluetooth,
    description: '휴대폰을 무선으로 연결해 통화·음악 재생.',
  },
  {
    key: 'carplay',
    label: '애플 카플레이',
    category: 'multimedia',
    icon: Smartphone,
    description: 'iPhone을 차량 디스플레이에 연결해 내비·메시지·음악 등을 사용.',
  },
  {
    key: 'android_auto',
    label: '안드로이드 오토',
    category: 'multimedia',
    icon: Cast,
    description: '안드로이드폰을 차량 디스플레이에 연결해 구글맵·메시지 등을 사용.',
  },
  {
    key: 'premium_sound',
    label: '프리미엄 사운드',
    category: 'multimedia',
    icon: Speaker,
    description: 'Bose·하만카돈 등 브랜드 사운드 시스템 장착.',
  },
  {
    key: 'rear_monitor',
    label: '후석 모니터',
    category: 'multimedia',
    icon: Tv,
    description: '뒷좌석 헤드레스트 후면에 설치된 영상 디스플레이.',
  },

  {
    key: 'leather_seat',
    label: '가죽시트',
    category: 'seat',
    icon: Armchair,
    description: '시트 표면이 천연 또는 인조 가죽으로 마감.',
  },
  {
    key: 'heated_seat',
    label: '열선시트',
    category: 'seat',
    icon: Flame,
    description: '시트 안의 열선으로 좌석을 따뜻하게 데움. 겨울철 유용.',
  },
  {
    key: 'ventilated_seat',
    label: '통풍시트',
    category: 'seat',
    icon: Wind,
    description: '시트 안의 팬으로 통풍을 일으켜 등·엉덩이 부분을 시원하게.',
  },
  {
    key: 'power_seat',
    label: '전동시트',
    category: 'seat',
    icon: Sofa,
    description: '시트의 전후·등받이 각도·높낮이를 모터로 조절.',
  },
  {
    key: 'rear_heated_seat',
    label: '후석 열선',
    category: 'seat',
    icon: Thermometer,
    description: '뒷좌석에도 열선 시트 적용. 동승자 겨울 편의성 향상.',
  },
  {
    key: 'massage_seat',
    label: '마사지시트',
    category: 'seat',
    icon: Hand,
    description: '시트 내장 모터가 등·허리를 압박하며 마사지.',
  },
  {
    key: 'heated_wheel',
    label: '열선 스티어링',
    category: 'seat',
    icon: Lifebuoy,
    description: '스티어링휠 림에 열선이 들어가 손잡이가 따뜻해짐.',
  },

  {
    key: 'alloy_wheel',
    label: '알로이휠',
    category: 'exterior',
    icon: CircleDot,
    description: '철 휠 대비 가볍고 디자인이 다양한 알루미늄 합금 휠.',
  },
  {
    key: 'led_head',
    label: 'LED 헤드램프',
    category: 'exterior',
    icon: Lightbulb,
    description: '할로겐·HID 대비 밝고 수명이 긴 LED 전조등.',
  },
  {
    key: 'matrix_led',
    label: '매트릭스 LED',
    category: 'exterior',
    icon: Layers,
    description: '전조등의 LED를 영역별로 제어해 마주오는 차량은 피하고 주변은 밝힘.',
  },
  {
    key: 'led_rear',
    label: 'LED 리어램프',
    category: 'exterior',
    icon: Sparkle,
    description: '후미등에 LED를 적용해 점등 속도가 빠르고 디자인이 선명.',
  },

  {
    key: 'hipass',
    label: '하이패스',
    category: 'etc',
    icon: CreditCard,
    description: '톨게이트를 정차 없이 통과할 수 있는 자동 결제 단말기.',
  },
  {
    key: 'blackbox',
    label: '블랙박스',
    category: 'etc',
    icon: Video,
    description: '주행·주차 중 영상을 녹화하는 카메라. 사고 증거 확보.',
  },
  {
    key: 'ecm_mirror',
    label: 'ECM 룸미러',
    category: 'etc',
    icon: SunMoon,
    description: '뒷차 헤드라이트 눈부심을 자동 감지해 룸미러를 어둡게 조절.',
  },
];
